### ISSUE TITLE
pingd flaky with >100 or so nodes

### ISSUE THREAD

**Issue by andrew-blueant** [chaos/whatsup#20]
I've been playing around with whatsup-pingd for use with pdsh -v.  It mostly operates well as long as there are less than 100 or so nodes in /etc/genders.

However, when I add a few hundred nodes, it'll only see that 40-60% are up, and the list of nodes that it thinks are up will fluctuate every few seconds.  I assume that it's sending out lots of pings and not getting or not handling the responses.

I've tried ping_period with 5000, 15000, and 60000, and it doesn't seem to make a difference.

Are there any debugging steps I can take or system resources I can modify to maybe get it to work?

Thanks.

**Comment by chu11** [comment]
I know others have had success w/ pingd at much larger scales, so my suspicion is your network is dropping packets.  The ping_period probably does not matter b/c the pings aren't staggered, they are just blasted out all at once.

I can't look it up right now, but there is a way to see socket stats on the linux command line, probably via `/proc/net/raw`.  You can see if the pingd daemon is dropping a lot of packets.  If it is, we can try and increase the socket receive buffer size.  There's a way to do that by being an admin but I can't remember how.  If that works, I could implement some code to adjust the socket receive buffer in pingd specifically. (Sorry, not at computer to lookup stuff more closely)

Other than that, I think I'd have to adjust pingd code to stagger the sending out of pings so it doesn't flood the network so much.

**Comment by andrew-blueant** [comment]
This is the line in /proc/net/raw that disappears when I stop pingd and reappears when I start it:

```
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode ref pointer drops
 152: 00000000:0001 00000000:0000 07 00001B00:00000000 00:00000000 00000000     0        0 253209 2 0000000000000000 736
```

The number in the "drops" column jumps up every ping_period seconds, so you're definitely on the right track with that.

Some sysctl settings I've tried that didn't help:

```
sudo sysctl net.ipv4.icmp_msgs_per_sec=10000
sudo sysctl net.ipv4.icmp_ratelimit=5
sudo sysctl net.ipv4.icmp_msgs_burst=1000
sudo sysctl net.core.rmem_max=6291456
sudo sysctl net.core.wmem_max=6291456
```

I'm open to any further suggestions, and I'll keep Googling to see what else I can dig up.

**Comment by chu11** [comment]
Googling a bit, I think what you want to try is `net.core.rmem_default` which changes the default.  The `_max` fields change the legal maximum that can be configured via calls to `setsockopt()`.

If that works for you at scale, I could add a config option in pingd that would you to configure a larger buffer size.

I should probably also stagger the pings.

**Comment by andrew-blueant** [comment]
That worked, thanks!

Staggered ping also sounds great.

I've noticed that when I add nodes to /etc/genders, pingd sees the new nodes but doesn't see them as being up until I restart the daemon.  Should I open a new issue for that?

**Comment by chu11** [comment]
Out of curiosity what is the default buffer size and what did you set it to, and for how many hosts.

> I've noticed that when I add nodes to /etc/genders, pingd sees the new nodes but doesn't see them as being up until I restart the daemon. Should I open a new issue for that?

Feel free too as a feature request to have pingd update itself given /etc/genders.

**Comment by chu11** [comment]
oh yeah, keep in mind that setting `net.core.rmem_default` is for all sockets on your system.  I can't speak to how that may or may not affect everything else on your system.

**Comment by andrew-blueant** [comment]
We've got about 500 nodes.

System default, before I changed anything: 212992

First try, x4, didn't quite work: 851968

Second try, x8, worked: 1703936

**Comment by chu11** [comment]
Just thinking about this a bit more, probably not going to implement staggering, as pingd simply wasn't designed for it.  Since pingd is single threaded, packets can't be taken off the buffer quick enough.   Since pingd was intentionally simple, not going to go down that path.

As an aside, I find it interesting that the 212992 buffer isn't big enough.  I can't remember the exact size of a ping packet once all the headers are added, but a quick Googling suggests its 56 or 84 bytes.  So it should hold more than enough for a "round" of 500 ping responses.  Dunno what could be going on in your network.

But regardless, I can add a receive buffer config option.

**Comment by chu11** [comment]
@andrew-boatrocker could you checkout the code in PR #22 and see if it fixes your problem.  The new config option is "ping_socket_receive_buffer BYTECOUNT".   Here's the patch file if you just want do apply it.

https://github.com/chaos/whatsup/commit/4a014b50daaaa143dd98f38fb64f922b81b48667.patch

**Comment by andrew-blueant** [comment]
I'm trying to get it working at all and am failing so far.  I originally installed from RPM, so I assume there's something wrong with my build environment.

First problem:

With /usr/local/sbin/pingd running and connected to port 9125, /usr/local/bin/whatsup reports "Cannot connect to server."  The whatsup that I installed from the RPM lists all nodes as being down.

```
$ ps ax | grep pingd
 846416 ?        S      0:00 /usr/local/sbin/pingd
$ sudo netstat -tunlp | grep pingd
tcp        0      0 0.0.0.0:9125            0.0.0.0:*               LISTEN      846416/pingd
$ /usr/local/bin/whatsup
whatsup: Cannot connect to server
$ /usr/bin/whatsup
up:     0:
down: 536: drn[001-080,101-172],ern[001-196],grn[001-104],hrn[17001-17084]
```
I tried copying the genders file from /etc to /usr/local/etc, but it didn't make any difference.

Second problem:

```
$ sudo make uninstall
[...snip...]
make[2]: Entering directory 'whatsup/src/Nodeupdown'
/bin/sh: -c: line 3: syntax error near unexpected token `.+'
/bin/sh: -c: line 3: `dir='/usr/local/`/usr/bin/perl -e 'use Config; $T=$Config{"installvendorarch"}; $T=~/^\Q$Config{"vendorprefix"}\E\/(.+)/; print $1;'`'; { test -z "$files" || { test ! -d "$dir" && test ! -f "$dir" && test ! -r "$dir"; } || { echo " ( cd '$dir' && rm -f" $files ")"; CDPATH="${ZSH_VERSION+.}:" && cd "$dir" && rm -f $files; }; }'
make[2]: *** [Makefile:440: uninstall-NODEUPDOWNPMFILESDATA] Error 2
```

**Comment by chu11** [comment]
Hmmm, does the following work for you to make a temporary rpm?

```
> ./configure
> make
> make dist
> rpmbuild -ta whatsup-1.14.1.tar.gz
```

if you don't have a .rpmmacros file, maybe being root would make this work.

**Comment by andrew-blueant** [comment]
Running as root, the rpmbuild step fails at:

```
RPM build errors:
    Directory not found: /root/rpmbuild/BUILDROOT/whatsup-1.14.1-1.x86_64/usr/lib64/whatsup
```

If you're able to build the rpms and send them to me, I'd be happy to test that way.  :-)

**Comment by chu11** [comment]
ok, lets try this instead

```
> make clean
> ./configure --enable-debug
> make
<setup pingd config file but also set pingd_server_port with a different port number than the default of 9125)
> src/pingd/pingd -c <your config file>
> src/whatsup/whatsup -p <port number you cnofigured>
```

with debug mode on, I think it'll load all plugins from the development directory and there won't be any `make install` path issues.

If I ultimately need to build you an rpm, what distro version?

**Comment by andrew-blueant** [comment]
I'm not sure if we're getting closer or not, lol:

```
$ src/pingd/pingd -c /etc/pingd.conf
pingd: unknown command line option 'c'
```

We're running Rocky 9.  Presumably RHEL 9 or any of its clones would be similar enough.

**Comment by chu11** [comment]
hmmmm.  does `--config-file=<file>` work?  does the option show up after you do `pingd --help`

(Oh, did you recompile .. I realize now that I should have added a "make" in my instructions above, updated it ... and added a make clean in for good measure)

Edit: Sorry, I now realize it's "--enable-debug" not "--with-debug" updated instructions above

**Comment by andrew-blueant** [comment]
```
$ src/pingd/pingd -h
Usage: pingd [OPTIONS]
-h    --help          Output Help
-v    --version       Output Version
$ src/pingd/pingd --config-file /etc/pingd.conf
Segmentation fault (core dumped)
$ git branch
  master
* pingd_receive_buffer
```

**Comment by andrew-blueant** [comment]
Ah, with --enable-debug I get the config option.  Will try now.

**Comment by andrew-blueant** [comment]
Hmm...

```
$ make clean
$ ./configure --enable-debug
$ make
$ src/pingd/pingd -c /etc/pingd.conf
pingd: (pingd_config.c, _load_module, 329): stat: filename=~/whatsup-chu11/whatsup/src/pingd/.libs/pingd_clusterlist_genders.so; No such file or directory
$ make clean
$ ./configure --enable-debug --with-pingd --with-genders
$ make
$ src/pingd/pingd -c /etc/pingd.conf
pingd: (pingd_config.c, _load_module, 329): stat: filename=~/whatsup-chu11/whatsup/src/pingd/.libs/pingd_clusterlist_genders.so; No such file or directory
```

Is there another switch I need to turn on to compile pingd with its own genders module?

**Comment by andrew-blueant** [comment]
Nevermind, got it with:

```
$ sudo yum install libgenders-devel
```

**Comment by andrew-blueant** [comment]
Closer:

```
$ sudo yum install libgenders-devel libnodeupdown-devel
$ make clean
$ ./configure --enable-debug
$ make
$ sudo src/pingd/pingd -d -c /etc/pingd.conf
```

And then in another shell:

```
$ src/whatsup/whatsup -p 9126
XML_ParseBuffer: Operation now in progress
lt-whatsup: _output_mode: nodeupdown_load_data(): internal system error
```

...and pingd crashes with:

```
Received pingd server request
pingd: (pingd_loop.c, _send_ping_data, 421): fd_write_n: Connection reset by peer
```

**Comment by chu11** [comment]
You shouldn't have to install libnodeupdown-devel, that will be built by whatsup.

so this is what I did to get things to work for me locally as a test

```
make clean
./configure --enable-debug --with-genders --with-pingd
make
sudo src/pingd/pingd -d -c ./foo.conf
```

my foo.conf is simply

```
ping_period 5000
pingd_server_port 9126
host corona212
host corona82
```

then in the other window

```
src/whatsup/whatsup -o localhost -p 9126 -m pingd
```

The -m is to force it to use pingd (just in case it was trying to communicate with someone else).  The `-o localhost` maybe shouldn't be necessary for you ... i forgot that my cluster has a conf that was pointing whatsup to another node by default.  But it couldn't hurt to use that too.

**Comment by andrew-blueant** [comment]
Working now.  "-m pingd" with whatsup is what saved pingd from crashing.

Now to test the new option:

```
$ cat foo.conf
ping_period 5000
pingd_server_port 9126
ping_socket_receive_buffer 1703936
```

Looks like it's working, but only if I first set the max receive buffer on the system:

```
$ sudo sysctl -w net.core.rmem_max=1703936
```

...which makes sense, I guess?

**Comment by chu11** [comment]
> ...which makes sense, I guess?

I don't know what your max was before, but if the max is too small it would have to be increased.

So it seems like it works.  I'll merge and do a release.

**Comment by andrew-blueant** [comment]
Thanks, and thanks for all your help working through this!

**Comment by chu11** [comment]
closing.  I assume that you installed whatsup via some distro (EPEL9?).  So you may want to ping em to try and bring down the newest release into the distro.  assuming it was EPEL I think this is the place.  https://src.fedoraproject.org/rpms/whatsup

**Comment by andrew-blueant** [comment]
I submitted a request to update EPEL here:

https://bugzilla.redhat.com/show_bug.cgi?id=2310844

The maintainer is asking, "Do you have any idea if 1.15 has any breaking changes compared to 1.14?"

What's the answer?

Thanks.
